---

- name: Ensure git installed
  hosts: centos 
  tags: [ 'install-git' ]
  tasks: 
  - package: name=git state=latest
    when: ansible_os_family == 'RedHat' # conditional task
    become: yes # https://docs.ansible.com/ansible/latest/user_guide/become.html
  # Note: since we have a group of centos hosts we don't really need the when condition but it is here to demo conditional tasks and in the event we have a mistake or a group that contains a host that isn't a RHEL derivative 

- name: Ensure ~/.gitconfig copied from master.gitconfig
  hosts: vagrant
  tasks:
  - name: first show no config in targets
    command: git config --global --list
    ignore_errors: yes 
      # https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html#ignoring-failed-commands
      # we know git config lookup will fail so ensure we don't stop playbook execution with ignore_errors
  - name: tried and true copy module with master.gitconfig from previously in the course 
    copy: src=master.gitconfig dest=~/.gitconfig
  - name: now, show newly added config!
    command: git config --global --list
    ignore_errors: yes


## Notes
# - This is a great read on error handling: https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html